### ISSUE TITLE
pre-commit checks: Remove duplicated checks in pylint-odoo

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#267]
Discuss the best way to deprecate duplicated checks of pre-commit.

Check the following comment:
https://github.com/OCA/maintainer-quality-tools/issues/623#issuecomment-567065945

Another example is the pylint-odoo check called javascript-lint it is duplicated using eslint in pre-commit.

And so on.

We need define a pylint-odoo version to deprecated all them.

Help is welcome!

**Comment by Yajo** [comment]
I was just gonna ask this about the js part. IMHO it should be removed from here, as it's gonna be out of sync soon.

**Comment by moylop260** [comment]
I agree
eslint must be deprecated from pylint-odoo

**Comment by moylop260** [comment]
@antonag32 

Could you remove all the custom lints that already exists from other lints compatible with pre-commit, please?

e.g. utf-8 comment, shebang, newlines, eslint and so on

And put in the commit message what is the replace, please?

Check the following pre-commit lints:

```yml
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: debug-statements
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
 - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: (Makefile|debian/rules|.gitmodules|\.po|\.pot)(\.in)?$
      - id: remove-tabs
        exclude: (Makefile|debian/rules|.gitmodules|\.po|\.pot)(\.in)?$
 - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
```
